routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [App\Http\Controllers\HomeController::class, 'index']);

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::group(['middleware'=>'auth'],function(){
    Route::resource('blog',App\Http\Controllers\BlogController::class);
    Route::resource('favorite_blog',App\Http\Controllers\FavoriteBlogController::class);
});

app/Models/Blog.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Blog extends Model
{
    use HasFactory;

    /**
     * The attributes that are mass assignable.
     *
     * @var string[]
     */
    protected $fillable = [
        'user_id',
        'title',
        'slug',
        'description',
        'start_date',
        'end_date',
        'image'
    ];

    public function scopeActive($query){
        return $query->where("isActive","1");
    }

    public function scopeUser($query){
        return $query->where("user_id",auth()->user()->id);
    }
}

app/Http/Controllers/BlogController.php
<?php

namespace App\Http\Controllers;

use App\Models\Blog;
use Illuminate\Http\Request;

class BlogController extends Controller
{
    
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

        if(auth()->user()->role == "0"){
            $blogs = Blog::user()->active()->get();
        }else{
            $blogs = Blog::active()->get();
        }
        return view('blog.index',compact('blogs'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('blog.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request,[
            'title' => 'required|unique:blogs,title',
            'description'=>'required',
            'start_date'=>'required',
            'end_date'=>'required',
            // 'image'=>'required'
        ]);
        

        try{
            $data = array();
            $data = $request->all();
            $data['start_date'] = date('Y-m-d',strtotime($request->start_date));
            $data['end_date'] = date('Y-m-d',strtotime($request->end_date));
            $data['slug'] = \Str::slug($request->title);
            if($request->hasFile('blog_image')){
                $image = time().rand(11,99)."_".rand(1111,9999)."_".rand(1,999999).'.'.$request->blog_image->extension();
                $request->blog_image->storeAs('blogs/',$image,'public');
                $data["image"] = $image;
            }
            $result = Blog::create($data);
            if($result){
                \Session::flash('message', 'Successfully saved');
                \Session::flash('alert-class', 'alert-success'); 
                return redirect()->route('blog.index');
            }else{
                \Session::flash('message', 'Successfully not saved');
                \Session::flash('alert-class', 'alert-danger'); 
                return redirect()->route('blog.index');
            }
        }catch(\Exception $e){
            \Session::flash('message', 'Something went wrong');
            \Session::flash('alert-class', 'alert-danger'); 
            return redirect()->route('blog.index');
        }

    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Blog  $blog
     * @return \Illuminate\Http\Response
     */
    public function show(Blog $blog)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Blog  $blog
     * @return \Illuminate\Http\Response
     */
    public function edit(Blog $blog)
    {
        $id = $blog->id;
        $blog = Blog::find($blog->id);
        return view('blog.edit',compact('blog','id'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Blog  $blog
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Blog $blog)
    {
        $this->validate($request,[
            'title' => 'required|unique:blogs,title,'.$blog->id,
            'description'=>'required',
            'start_date'=>'required',
            'end_date'=>'required',
        ]);
        

        try{
            $blog = Blog::find($blog->id);
            if($blog){
                $data = array();
                $data["description"] = $request->description;
                $data['start_date'] = date('Y-m-d',strtotime($request->start_date));
                $data['end_date'] = date('Y-m-d',strtotime($request->end_date));
                $data['slug'] = \Str::slug($request->title);
                if($request->hasFile('blog_image')){
                    \File::delete(public_path('storage/').'blogs/'.$blog->image);
                    $image = time().rand(11,99)."_".rand(1111,9999)."_".rand(1,999999).'.'.$request->blog_image->extension();
                    $request->blog_image->storeAs('blogs/',$image,'public');
                    $data["image"] = $image;
                }
                $result = Blog::where('id',$blog->id)->update($data);
                if($result){
                    \Session::flash('message', 'Successfully updated');
                    \Session::flash('alert-class', 'alert-success'); 
                    return redirect()->route('blog.index');
                }else{
                    \Session::flash('message', 'Successfully not updated');
                    \Session::flash('alert-class', 'alert-danger'); 
                    return redirect()->route('blog.index');
                }
            }else{
                abort(404);
            }
        }catch(\Exception $e){
            dd($e->getMessage());
            \Session::flash('message', 'Something went wrong');
            \Session::flash('alert-class', 'alert-danger'); 
            return redirect()->route('blog.index');
        }   
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Blog  $blog
     * @return \Illuminate\Http\Response
     */
    public function destroy(Blog $blog)
    {
        $blog = Blog::find($blog->id);
        if($blog){
            $blog->delete();
            \Session::flash('message', 'Successfully deleted');
            \Session::flash('alert-class', 'alert-success'); 
            return redirect()->route('blog.index');
        }else{
            \Session::flash('message', 'Successfully not deleted');
            \Session::flash('alert-class', 'alert-danger'); 
            return redirect()->route('blog.index');
        }
    }
}

resources/views/blog/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">
                    {{ __('Add Blog') }}
                    <a href="{{route('blog.index')}}" class="btn btn-primary btn-sm float-right">Back</a>
                </div>

                <div class="card-body">
                    <form method="POST" action="{{ route('blog.store') }}" enctype="multipart/form-data">
                        @csrf

                        <div class="form-group row">
                            <label for="title" class="col-md-4 col-form-label text-md-right">{{ __('Title') }}</label>

                            <div class="col-md-6">
                                <input id="title" type="text" class="form-control @error('title') is-invalid @enderror" name="title" value="{{ old('title') }}" required autocomplete="title" autofocus>

                                @error('title')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="description" class="col-md-4 col-form-label text-md-right">{{ __('Description') }}</label>

                            <div class="col-md-6">
                                <textarea name="description" id="description" style="resize: none;" class="form-control @error('description') is-invalid @enderror" required autocomplete="description" autofocus>{{ old('description') }}</textarea>

                                @error('description')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="start_date" class="col-md-4 col-form-label text-md-right">{{ __('Start Date') }}</label>

                            <div class="col-md-6">
                                <input id="start_date" type="text" class="datepicker form-control @error('start_date') is-invalid @enderror" name="start_date" value="{{ old('start_date') }}" required autocomplete="start_date" autofocus>

                                @error('start_date')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="end_date" class="col-md-4 col-form-label text-md-right">{{ __('End Date') }}</label>

                            <div class="col-md-6">
                                <input id="end_date" type="text" class="datepicker form-control @error('end_date') is-invalid @enderror" name="end_date" value="{{ old('end_date') }}" required autocomplete="end_date" autofocus>

                                @error('end_date')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label class="col-md-4 col-form-label text-md-right">{{ __('Image') }}</label>

                            <div class="col-md-6">
                                <input type="file" name="blog_image" accept="image/png, image/jpeg, image/jpg" class="form-control">

                                @error('blog_image')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row mb-0">
                            <div class="col-md-6 offset-md-4">
                                <input type="hidden" name="user_id" value="{{ auth()->user()->id }}">
                            </div>
                        </div>

                        <div class="form-group row mb-0">
                            <div class="col-md-6 offset-md-4">
                                <button type="submit" class="btn btn-primary">
                                    {{ __('Submit') }}
                                </button>
                            </div>
                        </div>

                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection


@section('extra_js')
<script>
    $(".datepicker").datepicker({
        format: 'dd-mm-yyyy',
    });
</script>
@endsection

resources/views/blog/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">
                    {{ __('Edit Blog') }}
                    <a href="{{route('blog.index')}}" class="btn btn-primary btn-sm float-right">Back</a>
                </div>

                <div class="card-body">
                    <form method="POST" action="{{ route('blog.update',[$id]) }}" enctype="multipart/form-data">
                        @csrf
                        @method('PATCH')

                        <div class="form-group row">
                            <label for="title" class="col-md-4 col-form-label text-md-right">{{ __('Title') }}</label>

                            <div class="col-md-6">
                                <input id="title" type="text" class="form-control @error('title') is-invalid @enderror" name="title" value="{{ $blog->title }}" required autocomplete="title" autofocus>

                                @error('title')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="description" class="col-md-4 col-form-label text-md-right">{{ __('Description') }}</label>

                            <div class="col-md-6">
                                <textarea name="description" id="description" style="resize: none;" class="form-control @error('description') is-invalid @enderror" required autocomplete="description" autofocus>{{ $blog->description }}</textarea>

                                @error('description')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="start_date" class="col-md-4 col-form-label text-md-right">{{ __('Start Date') }}</label>

                            <div class="col-md-6">
                                <input id="start_date" type="text" class="datepicker form-control @error('start_date') is-invalid @enderror" name="start_date" value="{{ date('d-m-Y',strtotime($blog->start_date)) }}" required autocomplete="start_date" autofocus>

                                @error('start_date')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="end_date" class="col-md-4 col-form-label text-md-right">{{ __('End Date') }}</label>

                            <div class="col-md-6">
                                <input id="end_date" type="text" class="datepicker form-control @error('end_date') is-invalid @enderror" name="end_date" value="{{ date('d-m-Y',strtotime($blog->end_date)) }}" required autocomplete="end_date" autofocus>

                                @error('end_date')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label class="col-md-4 col-form-label text-md-right">{{ __('Image') }}</label>

                            <div class="col-md-6">
                                <input type="file" name="blog_image" accept="image/png, image/jpeg, image/jpg" class="form-control">

                                @error('blog_image')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row mb-0">
                            <div class="col-md-6 offset-md-4">
                                <input type="hidden" name="user_id" value="{{ auth()->user()->id }}">
                            </div>
                        </div>

                        <div class="form-group row mb-0">
                            <div class="col-md-6 offset-md-4">
                                <button type="submit" class="btn btn-primary">
                                    {{ __('Submit') }}
                                </button>
                            </div>
                        </div>

                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection


@section('extra_js')
<script>
    $(".datepicker").datepicker({
        format: 'dd-mm-yyyy',
    });
</script>
@endsection

resources/views/blog/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            @if(Session::has('message'))
                <p class="alert {{ Session::get('alert-class', 'alert-info') }}">{{ Session::get('message') }}</p>
            @endif
            
            <a href="{{ route('blog.create') }}" class="btn btn-primary btn-sm float-right">Add Blog</a>

            <table class="table table-hover">
                <thead>
                  <tr>
                    <th>Title</th>
                    <th>Description</th>
                    <th>Start Date</th>
                    <th>End Date</th>
                    <th>Image</th>
                    <th>Action</th>
                  </tr>
                </thead>
                <tbody>
                    @if ($blogs->count() > 0)
                        @foreach ($blogs as $blog)
                            <tr>
                                <td>
                                    <img src="{{ asset('storage/blogs/'.$blog->image) }}" width="50" height="50">
                                </td>
                                <td>{{ $blog->title }}</td>
                                <td>{{ $blog->description }}</td>
                                <td>{{ date('d-m-Y',strtotime($blog->start_date)) }}</td>
                                <td>{{ date('d-m-Y',strtotime($blog->end_date)) }}</td>
                                <td>
                                    <a href="{{ route('blog.edit',$blog->id) }}">Edit</a>
                                    <form method="POST" action="{{route('blog.destroy',$blog->id)}}">
                                        {{ csrf_field() }}
                                        @method('DELETE')
                                        <button type="submit" name="delete" class="delete-photo" value="{{ $blog->id }}">Delete</button>
                                    </form>
                                </td>
                            </tr>
                        @endforeach
                    @else
                        <tr>
                            <td align="center" colspan="6">{{ __("No Record Found") }}</td>
                        </tr>
                    @endif
                </tbody>
            </table>
        </div>
    </div>
</div>
@endsection


@section('extra_js')
<script>
    $(".datepicker").datepicker({
        format: 'dd-mm-yyyy',
    });
</script>
@endsection